-- Pure Black Colorscheme for Neovim

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "pureblack"
vim.o.background = "dark"

local bg = "#000000"
local fg = "#e6e0bf"
local gray = "#48506a"
local light_gray = "#8b91a9"
local white = "#f3e9bd"
local red = "#e46876"
local green = "#98bb6c"
local yellow = "#f4d35e"
local blue = "#66a3ff"
local purple = "#957fb8"
local cyan = "#7aa89f"
local orange = "#ff9f43"
local gold = "#ffd700"       -- full moon yellow, main variables
local amber = "#ffdd57"      -- bright moonlight, parameters
local warm = "#ffea8a"       -- warm moon glow, properties

local hl = function(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

-- Editor
hl("Normal", { fg = fg, bg = bg })
hl("NormalFloat", { fg = fg, bg = bg })
hl("FloatBorder", { fg = gray, bg = bg })
hl("Cursor", { fg = bg, bg = fg })
hl("CursorLine", { bg = "#0a0a0a" })
hl("CursorColumn", { bg = "#0a0a0a" })
hl("ColorColumn", { bg = "#0a0a0a" })
hl("LineNr", { fg = gray })
hl("CursorLineNr", { fg = white, bold = true })
hl("SignColumn", { bg = bg })
hl("VertSplit", { fg = gray, bg = bg })
hl("WinSeparator", { fg = gray, bg = bg })
hl("StatusLine", { fg = white, bg = "#0a0a0a" })
hl("StatusLineNC", { fg = gray, bg = "#050505" })
hl("TabLine", { fg = gray, bg = "#050505" })
hl("TabLineFill", { bg = bg })
hl("TabLineSel", { fg = white, bg = bg })
hl("Pmenu", { fg = fg, bg = "#0a0a0a" })
hl("PmenuSel", { fg = white, bg = "#252525" })
hl("PmenuSbar", { bg = "#0a0a0a" })
hl("PmenuThumb", { bg = gray })
hl("WildMenu", { fg = white, bg = gray })
hl("Folded", { fg = light_gray, bg = "#0a0a0a" })
hl("FoldColumn", { fg = gray, bg = bg })
hl("MatchParen", { fg = white, bg = gray, bold = true })
hl("Visual", { bg = "#252525" })
hl("VisualNOS", { bg = "#252525" })
hl("Search", { fg = bg, bg = gold, bold = true })
hl("IncSearch", { fg = bg, bg = orange, bold = true })
hl("CurSearch", { fg = bg, bg = orange, bold = true })
hl("NonText", { fg = gray })
hl("SpecialKey", { fg = gray })
hl("Whitespace", { fg = gray })
hl("EndOfBuffer", { fg = bg })
hl("Directory", { fg = blue })
hl("Question", { fg = green })
hl("MoreMsg", { fg = green })
hl("ModeMsg", { fg = fg })
hl("ErrorMsg", { fg = red, bold = true })
hl("WarningMsg", { fg = yellow })
hl("Title", { fg = gold, bold = true })
hl("Conceal", { fg = light_gray })

-- Syntax
hl("Comment", { fg = light_gray, italic = true })
hl("Constant", { fg = orange })
hl("String", { fg = green })
hl("Character", { fg = green })
hl("Number", { fg = orange })
hl("Boolean", { fg = orange })
hl("Float", { fg = orange })
hl("Identifier", { fg = fg })
hl("Function", { fg = blue })
hl("Statement", { fg = purple })
hl("Conditional", { fg = purple })
hl("Repeat", { fg = purple })
hl("Label", { fg = purple })
hl("Operator", { fg = fg })
hl("Keyword", { fg = purple })
hl("Exception", { fg = purple })
hl("PreProc", { fg = cyan })
hl("Include", { fg = purple })
hl("Define", { fg = purple })
hl("Macro", { fg = cyan })
hl("PreCondit", { fg = cyan })
hl("Type", { fg = blue, bold = true })
hl("StorageClass", { fg = blue })
hl("Structure", { fg = blue, bold = true })
hl("Typedef", { fg = blue })
hl("Special", { fg = cyan })
hl("SpecialChar", { fg = cyan })
hl("Tag", { fg = blue })
hl("Delimiter", { fg = fg })
hl("SpecialComment", { fg = light_gray })
hl("Debug", { fg = red })
hl("Underlined", { fg = blue, underline = true })
hl("Ignore", { fg = gray })
hl("Error", { fg = red })
hl("Todo", { fg = bg, bg = gold, bold = true })

-- Diff
hl("DiffAdd", { fg = green, bg = "#0a1a0a" })
hl("DiffChange", { fg = yellow, bg = "#1a1a0a" })
hl("DiffDelete", { fg = red, bg = "#1a0a0a" })
hl("DiffText", { fg = orange, bg = "#1a1a0a", bold = true })

-- Diagnostics
hl("DiagnosticError", { fg = red })
hl("DiagnosticWarn", { fg = yellow })
hl("DiagnosticInfo", { fg = blue })
hl("DiagnosticHint", { fg = cyan })
hl("DiagnosticUnderlineError", { sp = red, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = yellow })
hl("DiagnosticUnderlineInfo", { sp = blue })
hl("DiagnosticUnderlineHint", { sp = cyan })

-- Git signs
hl("GitSignsAdd", { fg = green })
hl("GitSignsChange", { fg = yellow })
hl("GitSignsDelete", { fg = red })

-- Treesitter
hl("@variable", { fg = gold, bold = true })
hl("@variable.builtin", { fg = red })
hl("@variable.parameter", { fg = amber, bold = true })
hl("@parameter", { fg = amber, bold = true })
hl("@constant", { fg = orange })
hl("@constant.builtin", { fg = orange })
hl("@module", { fg = warm })
hl("@string", { fg = green })
hl("@string.escape", { fg = cyan })
hl("@character", { fg = green })
hl("@number", { fg = orange })
hl("@boolean", { fg = orange })
hl("@float", { fg = orange })
hl("@function", { fg = blue })
hl("@function.builtin", { fg = blue })
hl("@function.call", { fg = blue })
hl("@function.method", { fg = blue })
hl("@function.method.call", { fg = blue })
hl("@function.call.python", { fg = blue, bold = true })
hl("@constructor", { fg = blue, bold = true })
hl("@keyword", { fg = purple })
hl("@keyword.function", { fg = purple })
hl("@keyword.operator", { fg = purple })
hl("@keyword.return", { fg = purple })
hl("@keyword.conditional", { fg = purple })
hl("@keyword.repeat", { fg = purple })
hl("@keyword.import", { fg = purple })
hl("@operator", { fg = fg })
hl("@punctuation", { fg = fg })
hl("@punctuation.bracket", { fg = warm })
hl("@punctuation.delimiter", { fg = fg })
hl("@type", { fg = blue, bold = true })
hl("@type.builtin", { fg = blue })
hl("@type.definition", { fg = blue, bold = true })
hl("@attribute", { fg = cyan })
hl("@property", { fg = warm, bold = true })
hl("@field", { fg = warm, bold = true })
hl("@comment", { fg = light_gray, italic = true })
hl("@tag", { fg = blue })
hl("@tag.attribute", { fg = cyan })
hl("@tag.delimiter", { fg = fg })

-- LSP semantic tokens
hl("@lsp.type.class", { link = "@type" })
hl("@lsp.type.decorator", { fg = cyan })
hl("@lsp.type.enum", { link = "@type" })
hl("@lsp.type.enumMember", { fg = orange })
hl("@lsp.type.function", { fg = blue })
hl("@lsp.type.interface", { link = "@type" })
hl("@lsp.type.keyword", { link = "@keyword" })
hl("@lsp.type.macro", { fg = cyan })
hl("@lsp.type.method", { fg = blue })
hl("@lsp.type.namespace", { fg = warm })
hl("@lsp.type.number", { fg = orange })
hl("@lsp.type.operator", { fg = fg })
hl("@lsp.type.parameter", { fg = amber, bold = true })
hl("@lsp.type.property", { fg = warm, bold = true })
hl("@lsp.type.selfKeyword", { fg = red })
hl("@lsp.type.string", { fg = green })
hl("@lsp.type.type", { link = "@type" })
hl("@lsp.type.typeParameter", { fg = yellow, italic = true })
hl("@lsp.type.variable", { fg = gold, bold = true })
-- LSP modifier overrides (Pyright uses these for Python)
hl("@lsp.typemod.function.builtin", { fg = blue, italic = true })
hl("@lsp.typemod.variable.defaultLibrary", { fg = red })
hl("@lsp.typemod.variable.readonly", { fg = orange })
hl("@lsp.typemod.variable.declaration", { fg = gold, bold = true })
hl("@lsp.typemod.variable.globalScope", { fg = gold, bold = true })
hl("@lsp.typemod.class.defaultLibrary", { fg = yellow })
hl("@lsp.typemod.function.declaration", { fg = blue })
hl("@lsp.mod.parameter", { fg = amber, bold = true })
hl("@lsp.typemod.parameter.declaration", { fg = amber, bold = true })

-- Python (legacy syntax fallback when treesitter parser is absent)
hl("pythonFunction", { fg = blue })
hl("pythonDecorator", { fg = cyan })
hl("pythonDecoratorName", { fg = cyan })
hl("pythonAttribute", { fg = warm })
hl("pythonBuiltin", { fg = blue, italic = true })
hl("pythonSelf", { fg = red })
hl("pythonDottedName", { fg = warm })
hl("pythonImport", { fg = purple })
hl("pythonException", { fg = purple })
hl("pythonOperator", { fg = fg })
hl("pythonStatement", { fg = purple })
hl("pythonConditional", { fg = purple })
hl("pythonRepeat", { fg = purple })
hl("pythonClass", { fg = blue, bold = true })

-- Neo-tree
hl("NeoTreeNormal", { fg = fg, bg = bg })
hl("NeoTreeNormalNC", { fg = fg, bg = bg })
hl("NeoTreeVertSplit", { fg = gray, bg = bg })
hl("NeoTreeWinSeparator", { fg = gray, bg = bg })
hl("NeoTreeEndOfBuffer", { fg = bg, bg = bg })
hl("NeoTreeRootName", { fg = white, bold = true })
hl("NeoTreeGitAdded", { fg = green })
hl("NeoTreeGitConflict", { fg = red })
hl("NeoTreeGitDeleted", { fg = red })
hl("NeoTreeGitIgnored", { fg = gray })
hl("NeoTreeGitModified", { fg = yellow })
hl("NeoTreeGitUnstaged", { fg = yellow })
hl("NeoTreeGitUntracked", { fg = light_gray })
hl("NeoTreeGitStaged", { fg = green })

-- Telescope (if used)
hl("TelescopeNormal", { fg = fg, bg = bg })
hl("TelescopeBorder", { fg = gray, bg = bg })
hl("TelescopePromptNormal", { fg = fg, bg = bg })
hl("TelescopePromptBorder", { fg = gray, bg = bg })
hl("TelescopePromptTitle", { fg = white, bold = true })
hl("TelescopePreviewTitle", { fg = white, bold = true })
hl("TelescopeResultsTitle", { fg = white, bold = true })
hl("TelescopeSelection", { bg = "#252525" })
hl("TelescopeMatching", { fg = yellow, bold = true })

-- nvim-cmp
hl("CmpItemAbbrMatch", { fg = yellow, bold = true })
hl("CmpItemAbbrMatchFuzzy", { fg = yellow, bold = true })
hl("CmpItemKindVariable", { fg = fg })
hl("CmpItemKindFunction", { fg = blue })
hl("CmpItemKindMethod", { fg = blue })
hl("CmpItemKindKeyword", { fg = purple })
hl("CmpItemKindText", { fg = fg })
hl("CmpItemKindClass", { fg = yellow })
hl("CmpItemKindInterface", { fg = yellow })
hl("CmpItemKindModule", { fg = fg })
hl("CmpItemKindProperty", { fg = fg })
hl("CmpItemKindSnippet", { fg = cyan })
