-- Pure Black Colorscheme for Neovim (cterm only — driven by terminal palette)
--
-- ANSI slot reference (set these in your terminal app):
--  0  Black          → gutters, borders
--  1  Red            → variables, constants, numbers  (gold in pureblack palette)
--  2  Green          → parameters, warnings           (amber)
--  3  Yellow         → visual selection, search       (cream)
--  4  Blue           → keywords, errors, properties   (mauve)
--  5  Magenta        → very dark surfaces
--  6  Cyan           → functions, types               (warm gray)
--  7  White          → comments                       (dark gray)
--  8  Bright Black   → cursor line, subtle surfaces
--  9  Bright Red     → titles, emphasis               (near white)
-- 10  Bright Green   → strings                        (lime)
-- 11  Bright Yellow  → (unused / white)
-- 12  Bright Blue    → (same as Black)
-- 13  Bright Magenta → secondary UI                   (medium gray)
-- 14  Bright Cyan    → (white)
-- 15  Bright White   → (white)

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "pureblack"
vim.o.background = "dark"

local hl = function(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

local gold = 1 -- variables, constants
local amber = 2 -- parameters, warnings
local mauve = 4 -- keywords, errors, properties
local wgray = 6 -- functions, types
local dgray = 7 -- comments
local white = 9 -- emphasis
local lime = 10 -- strings
local mgray = 13 -- secondary UI

-- Editor
hl("Normal", {})
hl("NormalFloat", {})
hl("FloatBorder", { ctermfg = 0 })
hl("CursorLine", { ctermbg = 8 })
hl("CursorColumn", { ctermbg = 8 })
hl("ColorColumn", { ctermbg = 8 })
hl("LineNr", { ctermfg = 0 })
hl("CursorLineNr", { ctermfg = white, cterm = { bold = true } })
hl("SignColumn", {})
hl("VertSplit", { ctermfg = 0 })
hl("WinSeparator", { ctermfg = 0 })
hl("StatusLine", { ctermfg = white, ctermbg = 8 })
hl("StatusLineNC", { ctermfg = 0 })
hl("TabLine", { ctermfg = 0 })
hl("TabLineFill", {})
hl("TabLineSel", { ctermfg = white })
hl("Pmenu", { ctermbg = 8 })
hl("PmenuSel", { ctermfg = white, ctermbg = 5 })
hl("PmenuSbar", { ctermbg = 8 })
hl("PmenuThumb", { ctermbg = 0 })
hl("WildMenu", { ctermfg = white, ctermbg = 0 })
hl("Folded", { ctermfg = mgray, ctermbg = 8 })
hl("FoldColumn", { ctermfg = 0 })
hl("MatchParen", { ctermfg = white, ctermbg = 0, cterm = { bold = true } })
hl("Visual", { ctermbg = 3, ctermfg = 8 })
hl("VisualNOS", { ctermbg = 3, ctermfg = 8 })
hl("YankHighlight", { ctermbg = gold })
hl("Search", { ctermfg = 0, ctermbg = gold, cterm = { bold = true } })
hl("IncSearch", { ctermfg = 0, ctermbg = lime, cterm = { bold = true } })
hl("CurSearch", { ctermfg = 0, ctermbg = lime, cterm = { bold = true } })
hl("NonText", { ctermfg = 0 })
hl("SpecialKey", { ctermfg = 0 })
hl("Whitespace", { ctermfg = 0 })
hl("EndOfBuffer", { ctermfg = 0 })
hl("Directory", { ctermfg = wgray })
hl("Question", { ctermfg = lime })
hl("MoreMsg", { ctermfg = lime })
hl("ModeMsg", {})
hl("ErrorMsg", { ctermfg = mauve, cterm = { bold = true } })
hl("WarningMsg", { ctermfg = amber })
hl("Title", { ctermfg = gold, cterm = { bold = true } })
hl("Conceal", { ctermfg = mgray })

-- Syntax
hl("Comment", { ctermfg = dgray, cterm = { italic = true } })
hl("Constant", { ctermfg = gold })
hl("String", { ctermfg = lime })
hl("Character", { ctermfg = lime })
hl("Number", { ctermfg = gold })
hl("Boolean", { ctermfg = gold })
hl("Float", { ctermfg = gold })
hl("Identifier", {})
hl("Function", { ctermfg = wgray })
hl("Statement", { ctermfg = mauve })
hl("Conditional", { ctermfg = mauve })
hl("Repeat", { ctermfg = mauve })
hl("Label", { ctermfg = mauve })
hl("Operator", {})
hl("Keyword", { ctermfg = mauve })
hl("Exception", { ctermfg = mauve })
hl("PreProc", { ctermfg = wgray })
hl("Include", { ctermfg = mauve })
hl("Define", { ctermfg = mauve })
hl("Macro", { ctermfg = wgray })
hl("PreCondit", { ctermfg = wgray })
hl("Type", { ctermfg = wgray, cterm = { bold = true } })
hl("StorageClass", { ctermfg = wgray })
hl("Structure", { ctermfg = wgray, cterm = { bold = true } })
hl("Typedef", { ctermfg = wgray })
hl("Special", { ctermfg = wgray })
hl("SpecialChar", { ctermfg = wgray })
hl("Tag", { ctermfg = wgray })
hl("Delimiter", {})
hl("SpecialComment", { ctermfg = dgray })
hl("Debug", { ctermfg = mauve })
hl("Underlined", { ctermfg = wgray, cterm = { underline = true } })
hl("Ignore", { ctermfg = 0 })
hl("Error", { ctermfg = mauve })
hl("Todo", { ctermfg = 0, ctermbg = gold, cterm = { bold = true } })

-- Diff
hl("DiffAdd", { ctermfg = lime, ctermbg = 5 })
hl("DiffChange", { ctermfg = amber, ctermbg = 5 })
hl("DiffDelete", { ctermfg = mauve, ctermbg = 5 })
hl("DiffText", { ctermfg = gold, ctermbg = 8, cterm = { bold = true } })

-- Diagnostics
hl("DiagnosticError", { ctermfg = mauve })
hl("DiagnosticWarn", { ctermfg = amber })
hl("DiagnosticInfo", { ctermfg = wgray })
hl("DiagnosticHint", { ctermfg = wgray })
hl("DiagnosticUnderlineError", { cterm = { undercurl = true } })
hl("DiagnosticUnderlineWarn", { cterm = { underline = true } })
hl("DiagnosticUnderlineInfo", { cterm = { underline = true } })
hl("DiagnosticUnderlineHint", { cterm = { underline = true } })

-- Git signs
hl("GitSignsAdd", { ctermfg = lime })
hl("GitSignsChange", { ctermfg = amber })
hl("GitSignsDelete", { ctermfg = mauve })

-- Treesitter
hl("@variable", { ctermfg = gold, cterm = { bold = true } })
hl("@variable.builtin", { ctermfg = mauve })
hl("@variable.parameter", { ctermfg = amber, cterm = { bold = true } })
hl("@parameter", { ctermfg = amber, cterm = { bold = true } })
hl("@constant", { ctermfg = gold })
hl("@constant.builtin", { ctermfg = gold })
hl("@module", { ctermfg = mauve })
hl("@string", { ctermfg = lime })
hl("@string.escape", { ctermfg = wgray })
hl("@character", { ctermfg = lime })
hl("@number", { ctermfg = gold })
hl("@boolean", { ctermfg = gold })
hl("@float", { ctermfg = gold })
hl("@function", { ctermfg = wgray })
hl("@function.builtin", { ctermfg = wgray })
hl("@function.call", { ctermfg = wgray })
hl("@function.method", { ctermfg = wgray })
hl("@function.method.call", { ctermfg = wgray })
hl("@function.call.python", { ctermfg = wgray, cterm = { bold = true } })
hl("@constructor", { ctermfg = wgray, cterm = { bold = true } })
hl("@keyword", { ctermfg = mauve })
hl("@keyword.function", { ctermfg = mauve })
hl("@keyword.operator", { ctermfg = mauve })
hl("@keyword.return", { ctermfg = mauve })
hl("@keyword.conditional", { ctermfg = mauve })
hl("@keyword.repeat", { ctermfg = mauve })
hl("@keyword.import", { ctermfg = mauve })
hl("@operator", {})
hl("@punctuation", {})
hl("@punctuation.bracket", { ctermfg = mauve })
hl("@punctuation.delimiter", {})
hl("@type", { ctermfg = wgray, cterm = { bold = true } })
hl("@type.builtin", { ctermfg = wgray })
hl("@type.definition", { ctermfg = wgray, cterm = { bold = true } })
hl("@attribute", { ctermfg = wgray })
hl("@property", { ctermfg = mauve, cterm = { bold = true } })
hl("@field", { ctermfg = mauve, cterm = { bold = true } })
hl("@comment", { ctermfg = dgray, cterm = { italic = true } })
hl("@tag", { ctermfg = wgray })
hl("@tag.attribute", { ctermfg = wgray })
hl("@tag.delimiter", {})

-- LSP semantic tokens
hl("@lsp.type.class", { link = "@type" })
hl("@lsp.type.decorator", { ctermfg = wgray })
hl("@lsp.type.enum", { link = "@type" })
hl("@lsp.type.enumMember", { ctermfg = gold })
hl("@lsp.type.function", { ctermfg = wgray })
hl("@lsp.type.interface", { link = "@type" })
hl("@lsp.type.keyword", { link = "@keyword" })
hl("@lsp.type.macro", { ctermfg = wgray })
hl("@lsp.type.method", { ctermfg = wgray })
hl("@lsp.type.namespace", { ctermfg = mauve })
hl("@lsp.type.number", { ctermfg = gold })
hl("@lsp.type.operator", {})
hl("@lsp.type.parameter", { ctermfg = amber, cterm = { bold = true } })
hl("@lsp.type.property", { ctermfg = mauve, cterm = { bold = true } })
hl("@lsp.type.selfKeyword", { ctermfg = mauve })
hl("@lsp.type.string", { ctermfg = lime })
hl("@lsp.type.type", { link = "@type" })
hl("@lsp.type.typeParameter", { ctermfg = amber, cterm = { italic = true } })
hl("@lsp.type.variable", { ctermfg = gold, cterm = { bold = true } })
hl("@lsp.typemod.function.builtin", { ctermfg = wgray, cterm = { italic = true } })
hl("@lsp.typemod.variable.defaultLibrary", { ctermfg = mauve })
hl("@lsp.typemod.variable.readonly", { ctermfg = gold })
hl("@lsp.typemod.variable.declaration", { ctermfg = gold, cterm = { bold = true } })
hl("@lsp.typemod.variable.globalScope", { ctermfg = gold, cterm = { bold = true } })
hl("@lsp.typemod.class.defaultLibrary", { ctermfg = amber })
hl("@lsp.typemod.function.declaration", { ctermfg = wgray })
hl("@lsp.mod.parameter", { ctermfg = amber, cterm = { bold = true } })
hl("@lsp.typemod.parameter.declaration", { ctermfg = amber, cterm = { bold = true } })

-- Python legacy
hl("pythonFunction", { ctermfg = wgray })
hl("pythonDecorator", { ctermfg = wgray })
hl("pythonDecoratorName", { ctermfg = wgray })
hl("pythonAttribute", { ctermfg = mauve })
hl("pythonBuiltin", { ctermfg = wgray, cterm = { italic = true } })
hl("pythonSelf", { ctermfg = mauve })
hl("pythonDottedName", { ctermfg = mauve })
hl("pythonImport", { ctermfg = mauve })
hl("pythonException", { ctermfg = mauve })
hl("pythonOperator", {})
hl("pythonStatement", { ctermfg = mauve })
hl("pythonConditional", { ctermfg = mauve })
hl("pythonRepeat", { ctermfg = mauve })
hl("pythonClass", { ctermfg = wgray, cterm = { bold = true } })

-- Neo-tree
hl("NeoTreeNormal", {})
hl("NeoTreeNormalNC", {})
hl("NeoTreeVertSplit", { ctermfg = 0 })
hl("NeoTreeWinSeparator", { ctermfg = 0 })
hl("NeoTreeRootName", { ctermfg = white, cterm = { bold = true } })
hl("NeoTreeGitAdded", { ctermfg = lime })
hl("NeoTreeGitConflict", { ctermfg = mauve })
hl("NeoTreeGitDeleted", { ctermfg = mauve })
hl("NeoTreeGitIgnored", { ctermfg = 0 })
hl("NeoTreeGitModified", { ctermfg = amber })
hl("NeoTreeGitUnstaged", { ctermfg = amber })
hl("NeoTreeGitUntracked", { ctermfg = mgray })
hl("NeoTreeGitStaged", { ctermfg = lime })

-- Telescope
hl("TelescopeNormal", {})
hl("TelescopeBorder", { ctermfg = 0 })
hl("TelescopePromptNormal", {})
hl("TelescopePromptBorder", { ctermfg = 0 })
hl("TelescopePromptTitle", { ctermfg = white, cterm = { bold = true } })
hl("TelescopePreviewTitle", { ctermfg = white, cterm = { bold = true } })
hl("TelescopeResultsTitle", { ctermfg = white, cterm = { bold = true } })
hl("TelescopeSelection", { ctermbg = 5 })
hl("TelescopeMatching", { ctermfg = amber, cterm = { bold = true } })

-- nvim-cmp
hl("CmpItemAbbrMatch", { ctermfg = amber, cterm = { bold = true } })
hl("CmpItemAbbrMatchFuzzy", { ctermfg = amber, cterm = { bold = true } })
hl("CmpItemKindVariable", {})
hl("CmpItemKindFunction", { ctermfg = wgray })
hl("CmpItemKindMethod", { ctermfg = wgray })
hl("CmpItemKindKeyword", { ctermfg = mauve })
hl("CmpItemKindText", {})
hl("CmpItemKindClass", { ctermfg = amber })
hl("CmpItemKindInterface", { ctermfg = amber })
hl("CmpItemKindModule", {})
hl("CmpItemKindProperty", {})
hl("CmpItemKindSnippet", { ctermfg = wgray })
